const { spawnSync } = require('node:child_process');
const path = require('node:path');
const fs = require('node:fs');
const packageJson = require('../package.json');
const platform = process.platform;
const output = path.resolve('dist');
const candidates = platform === 'win32' ? ['win-unpacked/CodeGO ExamGuard.exe'] : platform === 'darwin' ? ['mac-arm64/CodeGO ExamGuard.app/Contents/MacOS/CodeGO ExamGuard','mac/CodeGO ExamGuard.app/Contents/MacOS/CodeGO ExamGuard'] : ['linux-unpacked/codego-examguard','linux-arm64-unpacked/codego-examguard'];
const executable = process.env.CODEGO_PACKAGED_EXECUTABLE || candidates.map(name=>path.join(output,name)).find(file=>fs.existsSync(file));
if (!executable) throw new Error('Compila el paquete nativo antes de comprobarlo.');
const report = path.resolve(`reports/packaged-${platform}-${process.arch}.json`);
const env = {...process.env, DEBUG:''};
delete env.ELECTRON_RUN_AS_NODE;
const args = [`--self-test-report=${report}`, '--disable-gpu'];
if (platform === 'linux') args.push('--ozone-platform=headless', `--ozone-override-screen-size=${process.env.CODEGO_TEST_SCREEN || '1440,900'}`, '--no-sandbox');
if (process.env.CODEGO_TEST_SCALE) args.push(`--force-device-scale-factor=${process.env.CODEGO_TEST_SCALE}`);
fs.mkdirSync(path.dirname(report),{recursive:true});
fs.rmSync(report,{force:true});
const result = spawnSync(executable,args,{env,stdio:'inherit',timeout:90000});
if (result.error) throw result.error;
if (result.status !== 0) process.exit(result.status || 1);
const evidence = JSON.parse(fs.readFileSync(report,'utf8'));
if (!evidence.success || !evidence.packaged || evidence.version !== packageJson.version || evidence.platform !== platform || evidence.arch !== process.arch) throw new Error('El paquete no superó la comprobación nativa.');
console.log(`Paquete verificado: ${platform}/${process.arch}, versión ${evidence.version}. Informe: ${report}`);
